vich_uploader:
    db_driver: orm

    metadata:
        type: attribute 
    mappings:
       Recettes:
           uri_prefix: /assets/rec
           upload_destination: '%kernel.project_dir%/public/assets/rec'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
           inject_on_load: true
